"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = '$time$all'

[directory]
format = 'in [$path]($style)[$read_only]($read_only_style) '

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[aws]
disabled = true

[gcloud]
disabled = true

[time]
disabled = false
format = '\[[$time]($style)\] '
