# BEGIN OH MY ZSH
# Location of oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"

export FZF_BASE="/usr/local/opt/fzf"

# Theme
# ZSH_THEME="spaceship"
ZSH_THEME="" # Load nothing as starship is loaded afterwards

# Plugins
plugins=(
  git
  yarn
  pnpm
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf
  autoupdate
  ayc0
)

# Spaceship config
# SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
# SPACESHIP_TIME_SHOW=true
# SPACESHIP_TIME_PREFIX="["
# SPACESHIP_TIME_SUFFIX="] "
# SPACESHIP_GCLOUD_SHOW=false
# SPACESHIP_AWS_SHOW=false

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

eval "$(starship init zsh)"

# Color folders and files
export LS_COLORS='no=00:fi=00:di=01;32:ln=36:pi=33:so=01;35:bd=01;33:cd=01;33:ex=01;31'
# END OH MY ZSH

# Load zoxide instead of cd
eval "$(zoxide init --cmd cd zsh)"

# BEGIN CUSTOM ALIASES
# Basic

alias less="/usr/local/bin/less"
alias cat="bat"

# Yarn
alias ytw="yarn test --watch"
localpnp () {
	local abs=`which $1`
	local resolved=`readlink -f $abs`
	shift
	echo "running yarn node $resolved $@"
	yarn node $resolved $@
}

# Fuck
eval $(thefuck --alias)

# SSHs
ssh-add -l > /dev/null || ssh-add --apple-load-keychain 2> /dev/null # save passphrase
# END CUSTOM ALIASES

# Node
export NODE_OPTIONS="--max-old-space-size=18192"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Slack
export SLACK_DEVELOPER_MENU=true

# Java
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# Disable typing a folder name
unsetopt autocd

export VOLTA_FEATURE_PNPM=1
